name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Initialize MySQL
      run: |
        sleep 15
        mysql --host 127.0.0.1 --port 3306 --user root --password=root -e 'SOURCE ffmeta/data/ffmetadata_ddl.sql;'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        PYTHONPATH=. python ffmeta/scripts/populate_tables.py --quiet

    - name: Run tests
      run: |
        pytest tests
